### ISSUE TITLE
remove unnecessary parents in pom files

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/freme-parent#3]
Every time starting to implement sth in a basic service etc I'm getting confused because my changes are not populated to the executed jars. This is often because some mediate pom files use old parent poms.
So why do the following pom files use freme-parent as parent:
- [controllers-parent](https://github.com/freme-project/basic-services/blob/master/controllers/pom.xml)
- [filters-parent](https://github.com/freme-project/basic-services/blob/master/filters/pom.xml)
- [basic-services-parent](https://github.com/freme-project/basic-services/blob/master/pom.xml)
- [e-service-parent](https://github.com/freme-project/e-services/blob/master/pom.xml)

In my opinion these poms do nothing than holding together the submodules, which have freme-parent as parent for themselves. For this functionality they neither have to inherit from freme-parent nor have to define repositories. Or do I miss something?

**Comment by jnehring** [comment]
> In my opinion these poms do nothing than holding together the submodules

They contain the modules section that points to the child artifacts. This is important because when you trigger mvn install or mvn deploy on the parent it triggers the same maven goal also on all child modules. This is important for Jenkins to work.

> they neither have to inherit from freme-parent

From freme-parent they inherit the distributionManagement tags.

> nor have to define repositories.

They have to define a repository because without the repository maven cannot not find the parent artifact. 

> my changes are not populated to the executed jars. This is often because some mediate pom files use old parent poms.

Lets say you change something in the pipelines basic service, version 0.9-SNAPSHOT. In order to add the new version as a dependency in some artifact (e.g. broker-dev) you have to:
- Check that the latest version of freme-parent defines the dependency on pipelines 0.9-SNAPSHOT
- Check that the artifact that should use the new version (e.g. broker-dev) uses the latest version of freme-parent.

One more thing you should note: Before the update of version numbers, the inheritance of basic services was like this:

`pipeline controller -> controller parent -> e-service parent -> freme-parent`

this is is long, complicated and error prone. I changed it to

`pipeline controller -> freme-parent`

because it is sufficient. When tracing version number errors you do not have to trace such long chains now.

**Comment by ArneBinder** [comment]
Thanks a lot for this clarification! 
From my point, we can close this.
